### ISSUE TITLE
code bug in keras_CIFAR10_simple.py

### ISSUE THREAD

**Issue by amiltonwong** [PacktPublishing/Deep-Learning-with-Keras#2]
Hi, authors,

In this [line](https://github.com/PacktPublishing/Deep-Learning-with-Keras/blob/master/Chapter03/keras_CIFAR10_simple.py#L45), it should be `input_shape=(IMG_CHANNELS, IMG_ROWS, IMG_COLS)` as the CIFAR 10 is loaded in the shape (num, channels, rows, columns)

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
