### ISSUE TITLE
Serialise and reuse the model using a random sentence

### ISSUE THREAD

**Issue by Munduruca** [PacktPublishing/Deep-Learning-with-Keras#6]
Hi! 
First of all, I would like to say that I'm enjoying the book a lot so far! Good job!

What I would like to know is:

1. how to serialise/save the model (SOLVED)
(found it! at https://keras.io/getting-started/faq/#how-can-i-use-pre-trained-models-in-keras)

2.how to load and re-use the model passing a random sentence.
Thank you in advance!

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if this error still exists. Thanks!
