### ISSUE TITLE
could you please provide dataset umich-sentiment-train.txt as well?

### ISSUE THREAD

**Issue by G-wave** [PacktPublishing/Deep-Learning-with-Keras#9]
Hello, I download the dataset from Kaggle, but it does not work. seem your dataset is . binary?

**Comment by ghost** [comment]
Here is part of code which you need to paste instead from the book


```
maxlen = 0
word_freqs = collections.Counter()
num_recs = 0
ftrain = open(os.path.join(DATA_DIR, "training.txt"), 'r')
for line in ftrain:
    label, sentence = line.strip().split("\t")    
    words = nltk.word_tokenize(sentence.lower())
    if len(words) > maxlen:
        maxlen = len(words)
    for word in words:
        word_freqs[word] += 1
    num_recs += 1
ftrain.close()
```

**Comment by gembin** [comment]
Where is `umich-sentiment-train.txt`?

**Comment by KinWaiCheuk** [comment]
@gembin 
The data can be found here
https://www.kaggle.com/c/si650winter11/data

You need to login first in order to see the download link.

**Comment by constantinembufung** [comment]
Just paste this code it will resolve the error you getting 
maxlen = 0
word_freqs = collections.Counter()
num_recs = 0
ftrain = open(os.path.join(DATA_DIR, "training.txt"), 'r')
for line in ftrain:
    label, sentence = line.strip().split("\t")    
    words = nltk.word_tokenize(sentence.lower())
    if len(words) > maxlen:
        maxlen = len(words)
    for word in words:
        word_freqs[word] += 1
    num_recs += 1
ftrain.close()

**Comment by BKD471** [comment]
> @gembin
> The data can be found here
> https://www.kaggle.com/c/si650winter11/data
> 
> You need to login first in order to see the download link.

but at that url kaggle has closed that data....and data is no longer available there
